### PR TITLE
Update for beta 8

### PR DESCRIPTION
**Pull request by glowingblue-dev**
This update needs to be reviewed as a lot of things have been changed, but it seems to work.

### CODE REVIEW

**Comment by dsevillamartin** [comment]
Thanks for the PR!

As we'll probably move this extension to FriendsOfFlarum, I'll merge this PR when we are ready for that (and then make the changes required for the migration).

Haven't looked at much of this, but removing the old migrations and treating them as if they never existed could cause issues for users that used this extension with beta 7, as the key would already exist in the settings table. However, this we can easily fix after merging.

**Comment by glowingblue-dev** [comment]
@datitisev Ok good, that would be great. 
You're right I didn't think about that case, thanks you for pointing it out !

**Comment by KyrneDev** [comment]
Hey @glowingblue,

Forumstyle completely breaks the emails on Gmail, can you remove the feature?

**Comment by glowingblue-dev** [comment]
@CDK2020 You mean completely remove it ? I though that making it optional would be a good solution.

**Comment by glowingblue-dev** [comment]
Does anyone know why the `EmailConfirmationMailer` is overridden ? The methods there send the emails using the `$mailer->raw()` method, so this should fallback to the PrettyMail `Mailer` class as it is set to be the default mailer in the `MailerProvider`. It was like that in beta 7 too so I am confused...

EDIT:
I now get it : the `EmailConfirmationMailer` gets the wrong Mailer instance as it asks for the `Illuminate\Contracts\Mail\Mailer` and not the `Reflar\PrettyMail\Mailer`. Therefore the raw method isn't the custom method that PrettyMail implements.

**Comment by dsevillamartin** [comment]
Thanks!

**Pull request merged**
